### ISSUE TITLE
Theme.AppCompat needed for VideoSessionActivity

### ISSUE THREAD

**Issue by albertocommure** [CirrusMD/CirrusMD-Android-SDK-Example#37]
Hello guys, 

I have been working recently with the implementation of the CirrusMD SDK and found out that both CirrusActivity and VideoSessionActivity extend from AppCompatActivity, but yet on the AndroidManifest.xml only the CirrusActivity defines a theme that extends Theme.AppCompat.

So, when trying to launch the video session, our app was getting the exception:

`
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
`

We are implementing the SDK in flutter and it turns out that when a Flutter project is created, the default theme is not an AppCompat theme.

So I wonder if there is a specific reason for one of the Activities having the theme defined and not the other activities that extend AppCompatActivity.

**Comment by DanielGalarza** [comment]
@albertocommure Hello! And apologies on the late response. It looks like this might just be a small oversight on our end, but we will be including a fix for this by adding `android:theme="@style/Theme.AppCompat.NoActionBar"` in the AndroidManifest for the VideoSessionActivity.

The plan is to have this resolved with our `9.0.0` release, which should be available mid June. Please let me know if you have any other questions or concerns.

**Comment by DanielGalarza** [comment]
@albertocommure Closing this issue, since this is now fixed in our 9.0.0 release: https://jitpack.io/#CirrusMD/cirrusmd-android/9.0.0
