### ISSUE TITLE
Video call is not closing when provider hangs up

### ISSUE THREAD

**Issue by danielmurcia** [CirrusMD/CirrusMD-Android-SDK-Example#40]
Hello there,

We've been working recently with your SDK and just found that when in a video call, as the provider hangs up, the video Activity background turns to white and it doesn't close, until the user taps the back button.

![cirrus white screen](https://user-images.githubusercontent.com/4340905/119899604-f1110480-bf08-11eb-925c-1378bdc24ff0.png)

Is this expected?

**Comment by taylorjcase** [comment]
This is expected behavior. Previously we did not have a way of resolving this due to a third party dependency. However, there is a new version of that dependency available that may help us resolve this in a future release.

**Comment by DanielGalarza** [comment]
@danielmurcia This issue has been resolved in v9.5.0!
