### ISSUE TITLE
Programmatically close CirrusMD activity

### ISSUE THREAD

**Issue by derekpitts28** [CirrusMD/CirrusMD-Android-SDK-Example#45]
I need to be able to close the CirrusMD activity programmatically to support deep linking and auth refreshing. As I can see there is no way to close your activity programmatically. 

Is there a way to do this current? Do you have a fragment implementation instead? Can you implement a broadcast receiver to accept intents to close the activity?

This is currently hindering our ability to maintain auth state within the app due to the rigidity of the CirrusMD Activity  implementation.

**Comment by DanielGalarza** [comment]
@derekpitts28 If you are able to grab a reference to the `CirrusActivity`, you should be able to call `finish()` on it. I believe some other customers have used `ActivityLifecycleCallbacks`  to get a reference, in the past. This callback is registered in your Application class. Although, this isn't a great approach, since it could promote memory leaks if the reference to the activity is stored

```
        registerActivityLifecycleCallbacks(object : ActivityLifecycleCallbacks {
            override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {}
            override fun onActivityStarted(activity: Activity) {}
            override fun onActivityResumed(activity: Activity) {}
            override fun onActivityStopped(activity: Activity) {}
            override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}
            override fun onActivityDestroyed(activity: Activity) {}
        })
```

I will bring back the idea of implementing a broadcast receiver back to the team and get back to you on this!

**Comment by derekpitts28** [comment]
> @derekpitts28 If you are able to grab a reference to the `CirrusActivity`, you should be able to call `finish()` on it. I believe some other customers have used `ActivityLifecycleCallbacks` to get a reference, in the past. This callback is registered in your Application class. Although, this isn't a great approach, since it could promote memory leaks if the reference to the activity is stored
> 
> ```
>         registerActivityLifecycleCallbacks(object : ActivityLifecycleCallbacks {
>             override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {}
>             override fun onActivityStarted(activity: Activity) {}
>             override fun onActivityResumed(activity: Activity) {}
>             override fun onActivityStopped(activity: Activity) {}
>             override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}
>             override fun onActivityDestroyed(activity: Activity) {}
>         })
> ```
> 
> I will bring back the idea of implementing a broadcast receiver back to the team and get back to you on this!

Thanks for the quick reply! I will attempt to use the lifecycle callbacks! Side question: Are there any plans to implement the CirrusActivity as a fragment instead?

**Comment by DanielGalarza** [comment]
> > @derekpitts28 If you are able to grab a reference to the `CirrusActivity`, you should be able to call `finish()` on it. I believe some other customers have used `ActivityLifecycleCallbacks` to get a reference, in the past. This callback is registered in your Application class. Although, this isn't a great approach, since it could promote memory leaks if the reference to the activity is stored
> > ```
> >         registerActivityLifecycleCallbacks(object : ActivityLifecycleCallbacks {
> >             override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {}
> >             override fun onActivityStarted(activity: Activity) {}
> >             override fun onActivityResumed(activity: Activity) {}
> >             override fun onActivityStopped(activity: Activity) {}
> >             override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}
> >             override fun onActivityDestroyed(activity: Activity) {}
> >         })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will bring back the idea of implementing a broadcast receiver back to the team and get back to you on this!
> 
> Thanks for the quick reply! I will attempt to use the lifecycle callbacks! Side question: Are there any plans to implement the CirrusActivity as a fragment instead?

Hello,

Currently, there are no plans to implement a `Fragment` based approach. But, we are always trying to improve our developer experience, so we will make a note of this. Thank you for your feedback!

**Comment by derekpitts28** [comment]
Awesome thanks! Please let me know if the broadcast receiver get implemented. 💯

**Comment by DanielGalarza** [comment]
@derekpitts28 Just wanted to give you a quick update. We have added a new functionality in our SDK that will allow you to finish our Activity, without needing a reference. This will come out in our next release, and so will the documentation. 

Thank you!

**Comment by derekpitts28** [comment]
> @derekpitts28 Just wanted to give you a quick update. We have added a new functionality in our SDK that will allow you to finish our Activity, without needing a reference. This will come out in our next release, and so will the documentation.
> 
> Thank you!

Awesome, thanks!!
