### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by daespark** [CirrusMD/CirrusMD-Android-SDK-Example#67]
We started failing to fetch sdk out of blue.

It appears that your builds aren't working :
https://jitpack.io/com/github/CirrusMD/CirrusMD-Android-SDK-Example/11.4.0-CirrusMD-Example/build.log

**Comment by daespark** [comment]
Pretty much getting this: 
`Could not GET 'https://jitpack.io/com/github/CirrusMD/cirrusmd-android/10.4.0/cirrusmd-android-10.4.0.pom'. Received status code 401 from server: Unauthorized`
for all versions

**Comment by DanielGalarza** [comment]
@daespark Yes, this is an issue we are facing at the moment. We are trying to resolve this as quick as possible. If you need an .aar to unblock you, please contact your CirrusMD's Customer Success rep and they can get that request sent over to our devs

**Comment by daespark** [comment]
Do you have an eta for the fix?

**Comment by DanielGalarza** [comment]
@daespark It is back up and running now!
